[package]
authors = ["John Boyd <johnboydiv@gmail.com>"]
name = "dice-mnemonics"
description = "Generate a mnemonic phrase using dice rolls."
version = "0.1.0"

[dependencies]
clap = "2.32"
crc = "1.8"
rand = "0.5.5"